/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/link-passhref */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { Component } from "react";
import Navigation from ".//components/Navigation";
import Footer from ".//components/Footer";
import Link from "next/link";
import { Button, Row } from "@nextui-org/react";
class Index extends Component {
  state = {};
  render() {
    return (
      <div>
        <Head>
          <title>Support Ukrainian Students in the US</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navigation />
        <div>
          <div className={styles.frontImage}>
            <Image
              src="/Vector.svg"
              alt="Cover Image"
              layout="fill"
              objectFit="cover"
            />
          </div>
          <div>
            <h2 className={styles.h2}>
              <span className={styles.h2span}>Our Mission</span>
              <p className={styles.minortext}>
                {" "}
                Thank you for your interest in applying to be an Admission
                Ambassador. Admission Ambassadors not only give tours to
                prospective families, .{" "}
              </p>
              <div className={styles.classicButton}>
                <Link href="/donate">
                  <Button
                    rounded
                    color="warning"
                    className={styles.classicButton}
                  >
                    <p className={styles.button}> Donate</p>
                  </Button>
                </Link>
              </div>
            </h2>
          </div>
        </div>

        <main className={styles.main}>
          <h1 className={styles.title}>Support Ukrainian Students in the US</h1>
          <hr size="7" width="60%" className={styles.mainhr} />
          <span className={styles.aboutMainCard}>
            <span className={styles.donateCards}>
              <span className={styles.verticalLine2}></span>
              <div className={styles.donateImage}>
                <h1 className={styles.regish1}>
                  A student-run nonprofit that aims to support Ukrainian
                  students in the US.
                </h1>
                <div className={styles.mainButton}>
                  <Link href="/about">
                    <Button rounded>
                      <p className={styles.Registerbutton}> More About Us</p>
                    </Button>
                  </Link>
                </div>
              </div>
              <div className={styles.donateText}>
                <div className={styles.mainSmallText}>
                  Thank you for your interest in applying to be an Admission
                  Ambassador. Admission Ambassadors not only give tours to
                  prospective families, but also play a significant role in the
                  execution of admission events including Discover Webb Day,
                  Revisit Day and other events as necessary throughout the
                  school year. Thank you for your interest in applying to be an
                  Admission Ambassador.
                </div>
              </div>
            </span>
          </span>
        </main>
        <div className={styles.divDonate}></div>
        <main className={styles.mainOfNews}>
          <h1 className={styles.newsTitle}>News Surrounding the Issue</h1>
          <div className={styles.newsDes}>
            The ongoing war has a huge impact on Ukrainian students who are
            studying abroad here are a few article that highlight this issue
          </div>

          <span className={styles.mainNewsCard}>
            <span className={styles.newsText1}>
              <div style={{ borderRadius: "20px", overflow: "hidden" }}>
                <Image
                  src="/news1.svg"
                  alt="news1 Image"
                  width={400}
                  height={270}
                  objectFit="cover"
                />
              </div>
              <div className={styles.newsTitleText}>
                "U.S. Colleges, and Their Russian and Ukrainian Students, Are
                Caught Up In a Crisis" TIME
              </div>
              <Row
                justify="center"
                style={{
                  marginTop: "15px",
                }}
              >
                <a
                  href="https://time.com/6154517/russian-ukrainian-college-students-u-s/"
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ textDecoration: "none" }}
                >
                  <Button rounded className={styles.button} color="warning">
                    Read More
                  </Button>
                </a>
              </Row>
            </span>
            <span className={styles.newsText2}>
              <div style={{ borderRadius: "20px", overflow: "hidden" }}>
                <Image
                  src="/news2.svg"
                  alt="news2 Image"
                  width={400}
                  height={270}
                  objectFit="cover"
                />
              </div>
              <div className={styles.newsTitleText}>
                "Ukrainian students in the U.S. watch a war on their homeland
                unfold from abroad" NPR
              </div>
              <Row
                justify="center"
                style={{
                  marginTop: "15px",
                }}
              >
                <a
                  href="https://www.npr.org/2022/03/20/1087766118/ukrainian-students-us-colleges#:~:text=Some%201%2C700%20Ukrainians%20are%20studying,from%20thousands%20of%20miles%20away."
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ textDecoration: "none" }}
                >
                  <Button rounded className={styles.button} color="warning">
                    Read More
                  </Button>
                </a>
              </Row>
            </span>
            <span className={styles.newsText3}>
              <div style={{ borderRadius: "20px", overflow: "hidden" }}>
                <Image
                  src="/news3.svg"
                  alt="news Image"
                  width={400}
                  height={270}
                  objectFit="cover"
                />
              </div>
              <div className={styles.newsTitleText}>
                "Ukrainian students in the U.S. face emotional, financial
                hardships" Marketplace
              </div>
              <Row
                justify="center"
                style={{
                  marginTop: "15px",
                }}
              >
                <a
                  href="https://www.marketplace.org/2022/03/07/ukrainian-students-u-s-face-emotional-financial-hardships/"
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ textDecoration: "none" }}
                >
                  <Button rounded className={styles.button} color="warning">
                    Read More
                  </Button>
                </a>
              </Row>
            </span>
          </span>
        </main>
        <Footer />
      </div>
    );
  }
}

export default Index;
