import Navigation from ".//components/Navigation";
import Footer from ".//components/Footer";
import LogTable from ".//components/table";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Head from "next/head";
import { BsClockFill } from "react-icons/bs";

export default function Log() {
  return (
    <div>
      <Head>
        <title>Activity Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Image
        src="/logpage.svg"
        alt="Log Page Image"
        width={2000}
        height={600}
        objectFit="cover"
      />
      <div>
        <h2 className={styles.h2}>
          <span className={styles.h2spanLog}>Transparency Notice</span>
          <p className={styles.minortext}>
            {" "}
            Thank you for your interest in applying to be an Admission
            Ambassador. Admission Ambassadors not only give tours to prospective
            families, .{" "}
          </p>
        </h2>
      </div>
      <div
        className={styles.divDonate}
        style={{
          height: "800px",
        }}
      >
        <span className={styles.mainLogCard}></span>
        <span
          className={styles.donateLogCard}
          style={{
            top: "795px",
          }}
        ></span>
        <span
          className={styles.donateLogCard}
          style={{
            top: "1000px",
          }}
        ></span>
      </div>
      <div className={styles.table}>
        <p className={styles.update}>
          <BsClockFill />
          <span className={styles.updateText}>
            Last Update: 11 Apr 2022 11:57AM PST
          </span>
        </p>
        <LogTable />
      </div>
      <Footer />
    </div>
  );
}
